<<<<<<< HEAD
# Generated by Django 5.2.11 on 2026-02-09 08:35
=======
# Generated by Django 5.2.8 on 2026-02-10 15:25
>>>>>>> upstream/main

import crm.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DN_ID', models.CharField(default=crm.models.generate_dn_id, editable=False, max_length=20, unique=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('delivery_type', models.CharField(choices=[('Regular', 'Regular'), ('Urgent', 'Urgent'), ('Return', 'Return')], default='Regular', max_length=20)),
                ('destination_address', models.TextField(blank=True)),
                ('delivery_status', models.CharField(choices=[('Draft', 'Draft'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('partially_delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNR_ID', models.CharField(default=crm.models.generate_delivery_note_return_id, editable=False, max_length=20, unique=True)),
                ('dnr_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_reference_no', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='delivery_note_return_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('invoiced_qty', models.IntegerField(default=0)),
                ('returned_qty', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('enquiry_type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service'), ('Both', 'Both')], max_length=50)),
                ('enquiry_description', models.TextField(blank=True)),
                ('enquiry_channel', models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Email', 'Email'), ('Web Form', 'Web Form'), ('Social Media', 'Social Media'), ('Other', 'Other')], max_length=50)),
                ('social_media_platform', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('WhatsApp', 'WhatsApp')], max_length=50, null=True)),
                ('source', models.CharField(blank=True, choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Online Advertising', 'Online Advertising'), ('Offline Advertising', 'Offline Advertising'), ('Social Media', 'Social Media'), ('Event', 'Event'), ('Search Engine', 'Search Engine'), ('Other', 'Other')], max_length=50)),
                ('source_social_media', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('WhatsApp', 'WhatsApp')], max_length=50, null=True)),
                ('how_heard', models.CharField(blank=True, choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Social Media', 'Social Media'), ('Event', 'Event'), ('Search Engine', 'Search Engine'), ('Other', 'Other')], max_length=50)),
                ('urgency_level', models.CharField(blank=True, choices=[('Immediately', 'Immediately'), ('Within 1-3 Months', 'Within 1-3 Months'), ('Within 6 Months', 'Within 6 Months'), ('Just Researching', 'Just Researching')], max_length=50)),
                ('enquiry_status', models.CharField(choices=[('New', 'New'), ('In Process', 'In Process'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('product_description', models.CharField(max_length=500)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVOICE_ID', models.CharField(default=crm.models.generate_invoice_id, editable=False, max_length=20, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_ref_no', models.CharField(blank=True, max_length=50)),
                ('invoice_tags', models.CharField(blank=True, max_length=100)),
                ('terms_conditions', models.TextField(blank=True)),
                ('invoice_status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('payment_terms', models.CharField(choices=[('Net 15', 'Net 15'), ('Net 20', 'Net 20'), ('Net 45', 'Net 45'), ('Due on Receipt', 'Due on Receipt')], default='Net 30', max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('shipping_address', models.TextField(blank=True)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('COD', 'COD'), ('PayPal', 'PayPal')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR'), ('GBP', 'GBP'), ('SGD', 'SGD')], default='INR', max_length=3)),
                ('payment_ref_number', models.CharField(blank=True, max_length=50)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='invoice_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('returned_qty', models.IntegerField(default=0)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVOICE_RETURN_ID', models.CharField(default=crm.models.generate_invoice_return_id, editable=False, max_length=20, unique=True)),
                ('invoice_return_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_reference_no', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoice_return_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('invoiced_qty', models.IntegerField(default=0)),
                ('returned_qty', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('return_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_to_refund', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_summary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_note_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('customer_po_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation_type', models.CharField(choices=[('Standard', 'Standard'), ('Blanket', 'Blanket'), ('Service', 'Service')], default='Standard', max_length=50)),
                ('quotation_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('SGD', 'SGD')], default='INR', max_length=3)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Converted to SO', 'Converted to SO'), ('Expired', 'Expired')], default='Draft', max_length=20)),
                ('revise_count', models.PositiveIntegerField(default=0)),
                ('global_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotations/attachments/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('pdf_generated', 'PDF Generated'), ('email_sent', 'Email Sent')], default='status_change', max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_info', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(editable=False, max_length=200)),
                ('product_id_display', models.CharField(editable=False, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField()),
                ('revision_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(default='Submitted', max_length=20)),
            ],
            options={
                'ordering': ['-revision_no'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('order_type', models.CharField(choices=[('Standard', 'Standard'), ('Rush', 'Rush'), ('Backorder', 'Backorder')], default='Standard', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('SGD', 'SGD')], default='INR', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('shipping_method', models.CharField(blank=True, max_length=50)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('global_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready to Submit', 'Ready to Submit'), ('Submitted', 'Submitted'), ('Submitted(PD)', 'Submitted(PD)'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('pdf_generated', 'PDF Generated'), ('email_sent', 'Email Sent'), ('po_generated', 'PO Generated')], default='status_change', max_length=20)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_info', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(editable=False, max_length=200)),
                ('product_id_display', models.CharField(editable=False, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='delivery_note_attachments/')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.deliverynote')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteCustomerAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('proof_of_delivery', models.FileField(blank=True, null=True, upload_to='delivery_proof/')),
                ('delivery_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='crm.deliverynote')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deliverynote')),
            ],
        ),
    ]
