# Generated by Django 5.2.8 on 2025-12-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotationRevision',
        ),
    ]
