# Generated by Django 5.2.8 on 2025-12-09 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_delete_quotationrevision'),
        ('masters', '0003_alter_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.taxcode'),
        ),
    ]
