# Generated by Django 4.2.23 on 2025-11-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_quotationattachment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
