# Generated by Django 4.2.23 on 2025-11-24 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_alter_enquiry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='sales_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'Sales Representative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
