# Generated by Django 5.2.8 on 2026-02-05 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('masters', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='po_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier'),
        ),
        migrations.AddField(
            model_name='debitnoteattachment',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnoteitem',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnoteitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='debitnotepaymentrecover',
            name='debit_note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_recover', to='finance.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnoteremark',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnoteremark',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='finance.debitnote'),
        ),
    ]
