# Generated by Django 4.2.23 on 2025-11-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday')], default='Absent', max_length=10),
        ),
    ]
