# Generated by Django 5.2.8 on 2026-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='available_branches',
        ),
        migrations.AddField(
            model_name='customuser',
            name='available_branches',
            field=models.ManyToManyField(blank=True, related_name='users', to='masters.branch'),
        ),
    ]
