# Generated by Django 5.2.8 on 2025-12-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplier',
            table=None,
        ),
    ]
