# Generated by Django 5.2.8 on 2026-02-06 15:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_customer_options_customer_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='custom_payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='custom_supplier_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_custom_payment_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_custom_supplier_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='workflow_status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='avg_lead_time_days',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='defect_return_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='min_order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='on_time_delivery_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Wire Transfer', 'Wire Transfer'), ('ACH', 'ACH'), ('Check', 'Check'), ('Credit Card', 'Credit Card'), ('UPI', 'UPI')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 45', 'Net 45'), ('Net 60', 'Net 60'), ('Prepaid', 'Prepaid'), ('COD', 'COD'), ('Custom', 'Custom')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quality_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(blank=True, choices=[('Manufacturer', 'Manufacturer'), ('Distributor', 'Distributor'), ('Service Provider', 'Service Provider'), ('Trader', 'Trader'), ('Importer', 'Importer'), ('Other', 'Other'), ('Custom', 'Custom')], max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_id', 'status', 'tax_id'], name='masters_sup_supplie_aa0b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_name'], name='masters_sup_supplie_d1dfed_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('tax_id',), name='unique_supplier_tax_id'),
        ),
        migrations.AddField(
            model_name='supplierhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierhistory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='masters.supplier'),
        ),
    ]
